### ISSUE TITLE
Header block content fails to save/update and display on front-end.

### ISSUE THREAD

**Issue by chriswallace** [bigbitecreative/benenson#26] opened 2018-12-09 19:45 UTC
## Expected Behavior

Title, description, and button text should all be editable and update on the front end after saving the page.

## Actual Behavior

When creating a header block, the text content sometimes is impossible to edit or sometimes can be edited but fails to update and display properly on the front-end.

## Steps to Reproduce the Problem

  1. Add a Header block to a Gutenberg page.
  2. Edit the text in the title, description or button.
  3. Save the page.
  4. View the front-end.

## Specifications

  - Browser: Chrome 71.0.3578.80
  - Platform: Mac OS X Mojave

**Comment by jonmcp** [comment] 2018-12-10 10:11
Hi @chriswallace 

Thanks for your report. There is a workaround for this whilst we're working on a fix.
If it fails to save correctly, do the following:
1. Cut all of the text out of the content field (screenshot below)
    - Update other fields as required
2. Save the page
3. Paste the content back into the field
4. Re-save

This should do the trick. 

Thanks

![](http://bigbite.im/LuELyb+)

**Comment by jonmcp** [comment] 2018-12-12 10:42
Hey @chriswallace 

It appears to be caused by a bug in WP core; see this ticket on [trac](https://core.trac.wordpress.org/ticket/42069). Were you using WP v4 or WP v5 when you encountered this issue? The bug was patched in the 5.0 release.

Thanks

**Comment by chriswallace** [comment] 2018-12-12 15:45
5.0

**Comment by jrmd** [comment] 2018-12-17 14:36
Hi @chriswallace 

As I understand the failure to update error should've been fixed within WordPress 5.0, currently I'm struggling to recreate the issue locally to check the network requests. If at all possible when using this could you keep dev tools open on the network request and look for the post request that points to `yourdomain.com/wp-json/wp/v2/posts` and see what the response is. This will further help me understand whats causing this issue, and whether I need to file another issue with the Gutenberg editor.

Regarding being unable to edit the content sometimes, I have created a fix and filed a pull request.

Thanks,
Jerome

**Closed** 2019-01-17 15:32 UTC
Labels: [block] Header, bug
